image: docker:git
services:
- docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/appvelox-test-ci/websocket-chat-back
  
before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
- build

build:
  stage: build
  script:
  - docker build -t $CONTAINER_IMAGE .
  - docker push $CONTAINER_IMAGE
