FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY static/index.css /usr/share/nginx/static/index.css
COPY static/index.js /usr/share/nginx/static/index.js

